---

- include_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: virtual-users.yml
  when: vsftpd_enable_virt_users
